package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"cli-agent-gateway/internal/infra/envfile"
)

const defaultGatewaydAddr = "127.0.0.1:58473"

func WriteDefaultEnv(repoRoot, workdir string) (string, error) {
	envPath := filepath.Join(repoRoot, ".env")
	existing, err := envfile.Parse(envPath)
	if err != nil {
		return "", err
	}
	if err := migrateRuntimeKeys(repoRoot, existing); err != nil {
		return "", err
	}
	if err := migrateUserScopedKeys(repoRoot, existing); err != nil {
		return "", err
	}
	values := repoInitValues(workdir, existing)
	for key, value := range existing {
		spec, ok := LookupSpec(key)
		if ok && (spec.Scope == ScopeRuntimeDB || spec.Scope == ScopeUserEnv) {
			continue
		}
		if _, removed := removedEnvKeys[key]; removed {
			continue
		}
		if _, known := values[key]; !known {
			values[key] = value
		}
	}
	ordered := orderedRepoEnvKeys(values)
	headers := []string{
		fmt.Sprintf("# Auto-generated by gateway-cli config at %s", time.Now().Format(time.RFC3339)),
		"# Startup config only. Runtime tuning is stored in SQLite via `cag config set`.",
	}
	if err := envfile.Write(envPath, values, ordered, headers); err != nil {
		return "", err
	}
	return envPath, nil
}

func WriteUserEnv(gatewaydAddr string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	envPath := filepath.Join(home, ".cag", ".env")
	existing, err := envfile.Parse(envPath)
	if err != nil {
		return "", err
	}
	addr := strings.TrimSpace(gatewaydAddr)
	if addr == "" {
		addr = defaultGatewaydAddr
	}
	values := map[string]string{
		"GATEWAYD_ADDR": addr,
	}
	for k, v := range existing {
		if _, known := values[k]; !known {
			values[k] = v
		}
	}
	ordered := orderedUserEnvKeys(values)
	headers := []string{
		fmt.Sprintf("# Auto-generated by gateway-cli config --global at %s", time.Now().Format(time.RFC3339)),
		"# User-level defaults loaded by cag from ~/.cag/.env",
	}
	if err := envfile.Write(envPath, values, ordered, headers); err != nil {
		return "", err
	}
	return envPath, nil
}

func updateUserEnvValues(updates map[string]*string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	path := filepath.Join(home, ".cag", ".env")
	existing, err := envfile.Parse(path)
	if err != nil {
		return err
	}
	for key, ptr := range updates {
		k := normalizeKey(key)
		if ptr == nil {
			delete(existing, k)
			continue
		}
		v := strings.TrimSpace(*ptr)
		if v == "" {
			delete(existing, k)
			continue
		}
		existing[k] = v
	}
	headers := []string{
		fmt.Sprintf("# Auto-generated by gateway-cli config --global at %s", time.Now().Format(time.RFC3339)),
		"# User-level defaults loaded by cag from ~/.cag/.env",
	}
	return envfile.Write(path, existing, orderedUserEnvKeys(existing), headers)
}

func List(repoRoot string) ([]Entry, error) {
	return listEntries(repoRoot)
}

func Get(repoRoot, key string) (Entry, error) {
	return getEntry(repoRoot, key)
}

func Set(repoRoot, key, value string, global bool) (Entry, string, error) {
	spec, ok := LookupSpec(key)
	if !ok {
		return Entry{}, "", fmt.Errorf("unsupported config key: %s", strings.TrimSpace(key))
	}
	value = strings.TrimSpace(value)
	switch spec.Scope {
	case ScopeUserEnv:
		if !global {
			return Entry{}, "", fmt.Errorf("%s requires --global", spec.Key)
		}
		if err := updateUserEnvValues(map[string]*string{spec.Key: &value}); err != nil {
			return Entry{}, "", err
		}
		path, err := os.UserHomeDir()
		if err != nil {
			return Entry{}, "", err
		}
		if err := updateEnvFile(filepath.Join(repoRoot, ".env"), map[string]*string{spec.Key: nil}, orderedRepoEnvKeys(map[string]string{}), []string{
			fmt.Sprintf("# Auto-generated by gateway-cli config at %s", time.Now().Format(time.RFC3339)),
			"# Startup config only. Runtime tuning is stored in SQLite via `cag config set`.",
		}, removedEnvKeys); err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, filepath.Join(path, ".cag", ".env"), err
	case ScopeRepoEnv:
		if global {
			return Entry{}, "", fmt.Errorf("%s is repo-scoped and does not accept --global", spec.Key)
		}
		envPath := filepath.Join(repoRoot, ".env")
		headers := []string{
			fmt.Sprintf("# Auto-generated by gateway-cli config at %s", time.Now().Format(time.RFC3339)),
			"# Startup config only. Runtime tuning is stored in SQLite via `cag config set`.",
		}
		updates := map[string]*string{spec.Key: &value}
		if err := updateEnvFile(envPath, updates, orderedRepoEnvKeys(map[string]string{spec.Key: value}), headers, removedEnvKeys); err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, envPath, err
	case ScopeRuntimeDB:
		if global {
			return Entry{}, "", fmt.Errorf("%s is repo-scoped and does not accept --global", spec.Key)
		}
		updates := map[string]*string{spec.Key: &value}
		path, err := saveRuntimeValues(repoRoot, updates)
		if err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, path, err
	default:
		return Entry{}, "", fmt.Errorf("unsupported config scope for %s", spec.Key)
	}
}

func Unset(repoRoot, key string, global bool) (Entry, string, error) {
	spec, ok := LookupSpec(key)
	if !ok {
		return Entry{}, "", fmt.Errorf("unsupported config key: %s", strings.TrimSpace(key))
	}
	switch spec.Scope {
	case ScopeUserEnv:
		if !global {
			return Entry{}, "", fmt.Errorf("%s requires --global", spec.Key)
		}
		home, err := os.UserHomeDir()
		if err != nil {
			return Entry{}, "", err
		}
		path := filepath.Join(home, ".cag", ".env")
		if err := updateUserEnvValues(map[string]*string{spec.Key: nil}); err != nil {
			return Entry{}, "", err
		}
		if err := updateEnvFile(filepath.Join(repoRoot, ".env"), map[string]*string{spec.Key: nil}, orderedRepoEnvKeys(map[string]string{}), []string{
			fmt.Sprintf("# Auto-generated by gateway-cli config at %s", time.Now().Format(time.RFC3339)),
			"# Startup config only. Runtime tuning is stored in SQLite via `cag config set`.",
		}, removedEnvKeys); err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, path, err
	case ScopeRepoEnv:
		if global {
			return Entry{}, "", fmt.Errorf("%s is repo-scoped and does not accept --global", spec.Key)
		}
		path := filepath.Join(repoRoot, ".env")
		headers := []string{
			fmt.Sprintf("# Auto-generated by gateway-cli config at %s", time.Now().Format(time.RFC3339)),
			"# Startup config only. Runtime tuning is stored in SQLite via `cag config set`.",
		}
		if err := updateEnvFile(path, map[string]*string{spec.Key: nil}, []string{"CHANNEL_TYPE", "ACP_AGENT_CMD"}, headers, removedEnvKeys); err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, path, err
	case ScopeRuntimeDB:
		if global {
			return Entry{}, "", fmt.Errorf("%s is repo-scoped and does not accept --global", spec.Key)
		}
		path, err := saveRuntimeValues(repoRoot, map[string]*string{spec.Key: nil})
		if err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, path, err
	default:
		return Entry{}, "", fmt.Errorf("unsupported config scope for %s", spec.Key)
	}
}
