package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"cli-agent-gateway/internal/infra/envfile"
)

const defaultGatewaydAddr = "127.0.0.1:58473"

func WriteDefaultEnv(repoRoot, workdir string) (string, error) {
	_ = repoRoot
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	envPath := filepath.Join(home, ".cag", ".env")
	existing, err := envfile.Parse(envPath)
	if err != nil {
		return "", err
	}
	runtimeUpdates := map[string]*string{}
	for key, value := range existing {
		spec, ok := LookupSpec(key)
		if !ok || spec.Scope != ScopeRuntimeDB {
			continue
		}
		v := strings.TrimSpace(value)
		if v == "" {
			continue
		}
		copyValue := v
		runtimeUpdates[spec.Key] = &copyValue
	}
	if len(runtimeUpdates) > 0 {
		if _, err := saveRuntimeValues(repoRoot, runtimeUpdates); err != nil {
			return "", err
		}
	}
	values := userInitValues(workdir, existing)
	for key, value := range existing {
		spec, ok := LookupSpec(key)
		if ok && spec.Scope == ScopeRuntimeDB {
			continue
		}
		if _, removed := removedEnvKeys[key]; removed {
			continue
		}
		if _, known := values[key]; !known {
			values[key] = value
		}
	}
	ordered := orderedUserInitKeys(values)
	headers := []string{
		fmt.Sprintf("# Auto-generated by gateway-cli config at %s", time.Now().Format(time.RFC3339)),
		"# User-scoped gateway config loaded by cag from ~/.cag/.env.",
	}
	if err := envfile.Write(envPath, values, ordered, headers); err != nil {
		return "", err
	}
	return envPath, nil
}

func WriteUserEnv(gatewaydAddr string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	envPath := filepath.Join(home, ".cag", ".env")
	existing, err := envfile.Parse(envPath)
	if err != nil {
		return "", err
	}
	addr := strings.TrimSpace(gatewaydAddr)
	if addr == "" {
		addr = defaultGatewaydAddr
	}
	values := map[string]string{
		"GATEWAYD_ADDR": addr,
	}
	for k, v := range existing {
		if _, known := values[k]; !known {
			values[k] = v
		}
	}
	ordered := orderedUserEnvKeys(values)
	headers := []string{
		fmt.Sprintf("# Auto-generated by gateway-cli config --global at %s", time.Now().Format(time.RFC3339)),
		"# User-level defaults loaded by cag from ~/.cag/.env",
	}
	if err := envfile.Write(envPath, values, ordered, headers); err != nil {
		return "", err
	}
	return envPath, nil
}

func updateUserEnvValues(updates map[string]*string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	path := filepath.Join(home, ".cag", ".env")
	existing, err := envfile.Parse(path)
	if err != nil {
		return err
	}
	for key, ptr := range updates {
		k := normalizeKey(key)
		if ptr == nil {
			delete(existing, k)
			continue
		}
		v := strings.TrimSpace(*ptr)
		if v == "" {
			delete(existing, k)
			continue
		}
		existing[k] = v
	}
	headers := []string{
		fmt.Sprintf("# Auto-generated by gateway-cli config --global at %s", time.Now().Format(time.RFC3339)),
		"# User-level defaults loaded by cag from ~/.cag/.env",
	}
	return envfile.Write(path, existing, orderedUserEnvKeys(existing), headers)
}

func List(repoRoot string) ([]Entry, error) {
	return listEntries(repoRoot)
}

func Get(repoRoot, key string) (Entry, error) {
	return getEntry(repoRoot, key)
}

func Set(repoRoot, key, value string, global bool) (Entry, string, error) {
	spec, ok := LookupSpec(key)
	if !ok {
		return Entry{}, "", fmt.Errorf("unsupported config key: %s", strings.TrimSpace(key))
	}
	value = strings.TrimSpace(value)
	switch spec.Scope {
	case ScopeUserEnv:
		if err := updateUserEnvValues(map[string]*string{spec.Key: &value}); err != nil {
			return Entry{}, "", err
		}
		path, err := os.UserHomeDir()
		if err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, filepath.Join(path, ".cag", ".env"), err
	case ScopeRepoEnv:
		return Entry{}, "", fmt.Errorf("%s is no longer repo-scoped", spec.Key)
	case ScopeRuntimeDB:
		if global {
			return Entry{}, "", fmt.Errorf("%s is runtime-scoped and does not accept --global", spec.Key)
		}
		updates := map[string]*string{spec.Key: &value}
		path, err := saveRuntimeValues(repoRoot, updates)
		if err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, path, err
	default:
		return Entry{}, "", fmt.Errorf("unsupported config scope for %s", spec.Key)
	}
}

func Unset(repoRoot, key string, global bool) (Entry, string, error) {
	spec, ok := LookupSpec(key)
	if !ok {
		return Entry{}, "", fmt.Errorf("unsupported config key: %s", strings.TrimSpace(key))
	}
	switch spec.Scope {
	case ScopeUserEnv:
		home, err := os.UserHomeDir()
		if err != nil {
			return Entry{}, "", err
		}
		path := filepath.Join(home, ".cag", ".env")
		if err := updateUserEnvValues(map[string]*string{spec.Key: nil}); err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, path, err
	case ScopeRepoEnv:
		return Entry{}, "", fmt.Errorf("%s is no longer repo-scoped", spec.Key)
	case ScopeRuntimeDB:
		if global {
			return Entry{}, "", fmt.Errorf("%s is runtime-scoped and does not accept --global", spec.Key)
		}
		path, err := saveRuntimeValues(repoRoot, map[string]*string{spec.Key: nil})
		if err != nil {
			return Entry{}, "", err
		}
		entry, err := Get(repoRoot, spec.Key)
		return entry, path, err
	default:
		return Entry{}, "", fmt.Errorf("unsupported config scope for %s", spec.Key)
	}
}
